import type { Arrangement, ArrangementBlock, ArrangementTrack } from '../../deno/types.ts'
import { createId } from './create-id.ts'

export const ARRANGEMENT_VERSION = 1
export const DEFAULT_BLOCK_LENGTH_BARS = 4
export const DEFAULT_ARRANGEMENT_LENGTH_BARS = 16
export const DEFAULT_LANE_HEIGHT = 72
export const MIN_LANE_HEIGHT = 20
export const MAX_LANE_HEIGHT = 200
export const SNAP_STEPS_PER_BAR = 4
export const BEATS_PER_BAR = 4

const blockIdPrefix = 'lm-block-'
const trackIdPrefix = 'lm-track-'
const outputPipePattern = /\|>\s*(out|outs|solo|sout)\s*\(([^)]*)\)/g
const legacyEveryPattern = /\bevery\(\s*([^,()]+)\s*,\s*([^()]+?)\s*\)/g
const hypnosisCommunityTemplateId = 'community-c2i73g'
const obsoleteHypnosisFragments = [
  'piano(#1*o4,trig)',
  'pad($,every(1/2,1/8))',
  'trig:every(1/2,1/8)',
]

export function cloneArrangement(arrangement: Arrangement): Arrangement {
  return JSON.parse(JSON.stringify(arrangement)) as Arrangement
}

export function arrangementSignature(arrangement: Arrangement | null | undefined): string {
  return arrangement ? JSON.stringify(arrangement) : ''
}

export function createArrangementTrack(data: Partial<ArrangementTrack> = {}): ArrangementTrack {
  return {
    id: data.id ?? `${trackIdPrefix}${createId()}`,
    name: data.name ?? 'Lane',
    color: data.color ?? '#8b5cf6',
    volume: data.volume ?? 1,
    muted: data.muted ?? false,
    soloed: data.soloed ?? false,
    order: data.order ?? 0,
    height: clampLaneHeight(data.height ?? DEFAULT_LANE_HEIGHT),
  }
}

export function createArrangementBlock(data: Partial<ArrangementBlock> & Pick<ArrangementBlock, 'trackId'>): ArrangementBlock {
  return {
    id: data.id ?? `${blockIdPrefix}${createId()}`,
    trackId: data.trackId,
    startBar: data.startBar ?? 0,
    lengthBars: data.lengthBars ?? DEFAULT_BLOCK_LENGTH_BARS,
    name: data.name ?? 'Code block',
    color: data.color ?? '#22d3ee',
    templateId: data.templateId,
    code: migrateArrangementBlockCode({
      templateId: data.templateId,
      code: data.code ?? 'sine(a4)*ad(trig:every(1/8))',
    }),
    params: data.params ?? {},
    volume: data.volume ?? 1,
    muted: data.muted ?? false,
  }
}

export function createDefaultArrangement(code = ''): Arrangement {
  const track = createArrangementTrack({ name: 'Lane 1', order: 0, color: '#22d3ee' })
  const blockCode = code.trim() || 'drums()'
  const arrangement: Arrangement = {
    arrangementVersion: ARRANGEMENT_VERSION,
    bpm: 120,
    tracks: [track],
    blocks: [
      createArrangementBlock({
        trackId: track.id,
        name: code.trim() ? 'Legacy code' : 'Starter beat',
        color: track.color,
        startBar: 0,
        lengthBars: DEFAULT_ARRANGEMENT_LENGTH_BARS,
        code: stripOutputPipes(blockCode),
      }),
    ],
    generatedCode: '',
  }
  arrangement.generatedCode = compileArrangement(arrangement)
  return arrangement
}

export function normalizeArrangement(arrangement: Arrangement | undefined, legacyCode = ''): Arrangement {
  if (!arrangement) return createDefaultArrangement(legacyCode)
  const normalized = cloneArrangement(arrangement)
  normalized.arrangementVersion = ARRANGEMENT_VERSION
  normalized.bpm = Number.isFinite(normalized.bpm) ? normalized.bpm : 120
  normalized.tracks = normalized.tracks.length
    ? normalized.tracks.map((track, index) => createArrangementTrack({ ...track, order: track.order ?? index }))
    : createDefaultArrangement(legacyCode).tracks
  const fallbackTrackId = normalized.tracks[0]!.id
  normalized.blocks = normalized.blocks.map(block =>
    createArrangementBlock({
      ...block,
      trackId: normalized.tracks.some(track => track.id === block.trackId) ? block.trackId : fallbackTrackId,
      lengthBars: Math.max(0.25, block.lengthBars),
      startBar: Math.max(0, block.startBar),
    })
  )
  normalized.generatedCode = compileArrangement(normalized)
  return normalized
}

export function getArrangementLengthBars(arrangement: Arrangement): number {
  const blockEnd = arrangement.blocks.reduce((max, block) => Math.max(max, block.startBar + block.lengthBars), 0)
  return Math.max(DEFAULT_ARRANGEMENT_LENGTH_BARS, Math.ceil(blockEnd + 1))
}

export function snapBar(value: number): number {
  return Math.max(0, Math.round(value * SNAP_STEPS_PER_BAR) / SNAP_STEPS_PER_BAR)
}

export function clampLaneHeight(value: number): number {
  return Math.max(MIN_LANE_HEIGHT, Math.min(MAX_LANE_HEIGHT, value))
}

export function compileArrangement(input: Arrangement): string {
  const arrangement = cloneArrangement(input)
  const tracks = [...arrangement.tracks].sort((a, b) => a.order - b.order || a.name.localeCompare(b.name))
  const trackById = new Map(tracks.map(track => [track.id, track]))
  const hasSolo = tracks.some(track => track.soloed)
  const lines: string[] = [
    '// Generated by Loopmaster DAW arrangement. Edit blocks in the DAW view.',
    `bpm=${formatNumber(arrangement.bpm)}`,
    '',
  ]

  for (const track of tracks) {
    lines.push(`// Lane: ${escapeComment(track.name)}`)
  }
  lines.push('')

  const audibleBlocks = arrangement.blocks
    .filter(block => {
      const track = trackById.get(block.trackId)
      if (!track || block.muted || track.muted) return false
      if (hasSolo && !track.soloed) return false
      return block.lengthBars > 0
    })
    .sort((a, b) => a.startBar - b.startBar || a.name.localeCompare(b.name))

  if (!audibleBlocks.length) {
    lines.push('silence=dc(0)')
    lines.push('silence |> out($)')
    return lines.join('\n')
  }

  audibleBlocks.forEach((block, index) => {
    const track = trackById.get(block.trackId)!
    const id = `lm_${index}_${safeIdentifier(block.id)}`
    const start = snapBar(block.startBar)
    const end = snapBar(block.startBar + block.lengthBars)
    const startBeat = start * BEATS_PER_BAR
    const endBeat = end * BEATS_PER_BAR
    const volume = clamp(block.volume * track.volume, 0, 2)
    const blockCode = migrateArrangementBlockCode(block)

    lines.push(`// Block: ${escapeComment(block.name)} / ${escapeComment(track.name)}`)
    lines.push(`label(${formatNumber(start + 1)},'${escapeString(block.name)}',${index % 6})`)
    lines.push(`${id}_gate=step(${formatNumber(startBeat)},t)*(1-step(${formatNumber(endBeat)},t))`)
    if (isFullProjectBlock(blockCode)) {
      const source = prepareFullProjectBlockCode(blockCode, startBeat, `${id}_gate`, volume)
      lines.push(indent(source || 'dc(0)'))
    }
    else {
      const source = prepareBlockCode(blockCode, startBeat)
      lines.push(`${id}=()->{`)
      lines.push(indent(source || 'dc(0)'))
      lines.push('}')
      lines.push(`${id}()*${id}_gate*${formatNumber(volume)} |> out($)`)
    }
    lines.push('')
  })

  lines.push(`label(${formatNumber(getArrangementLengthBars(arrangement) + 1)},'end',0)`)
  return lines.join('\n').trimEnd()
}

function migrateArrangementBlockCode(block: Pick<ArrangementBlock, 'templateId' | 'code'>): string {
  let code = migrateLegacyEveryCalls(block.code)
  const shouldMigrateHypnosis = block.templateId === hypnosisCommunityTemplateId
    || obsoleteHypnosisFragments.every(fragment => code.includes(fragment))
  if (!shouldMigrateHypnosis) return code

  return code
    .replaceAll('piano(#1*o4,trig)', 'rhodes(#1*o4,trig)')
    .replaceAll('pad($,every(1/2,1/8))', 'supersaw($,7,.035)')
    .replaceAll('pad($,at(1/8,1/2))', 'supersaw($,7,.035)')
    .replaceAll('trig:every(1/2,1/8)', 'trig:at(1/8,1/2)')
}

function migrateLegacyEveryCalls(code: string): string {
  return code.replace(legacyEveryPattern, (_, every: string, offset: string) => `at(${offset.trim()},${every.trim()})`)
}

function prepareBlockCode(code: string, startBeat: number): string {
  const stripped = stripOutputPipes(code).trim()
  const shifted = stripped.replace(/\bt\b/g, 'bt')
  return [
    `bt=t-${formatNumber(startBeat)}`,
    shifted,
  ].filter(Boolean).join('\n')
}

function prepareFullProjectBlockCode(code: string, startBeat: number, gateName: string, volume: number): string {
  const shifted = code.trim().replace(/\bt\b/g, 'bt')
  const routed = shifted.replace(outputPipePattern, (_, fn: string, outputExpression: string) => {
    const expression = outputExpression.trim() || '$'
    return `|> ${fn}((${expression})*${gateName}*${formatNumber(volume)})`
  })
  return [
    `bt=t-${formatNumber(startBeat)}`,
    routed,
  ].filter(Boolean).join('\n')
}

function isFullProjectBlock(code: string): boolean {
  outputPipePattern.lastIndex = 0
  const outputCount = [...code.matchAll(outputPipePattern)].length
  outputPipePattern.lastIndex = 0
  return outputCount > 1 || /\bmix\s*=>/.test(code)
}

function stripOutputPipes(code: string): string {
  return code
    .replace(outputPipePattern, '')
    .trim()
}

function safeIdentifier(value: string): string {
  return value.replace(/[^a-zA-Z0-9_]/g, '_').replace(/^([^a-zA-Z_])/, '_$1')
}

function escapeComment(value: string): string {
  return value.replace(/\n/g, ' ').replace(/\s+/g, ' ').trim()
}

function escapeString(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, ' ')
}

function indent(value: string): string {
  return value.split('\n').map(line => `  ${line}`).join('\n')
}

function formatNumber(value: number): string {
  return Number.isInteger(value) ? String(value) : Number(value.toFixed(4)).toString()
}

function clamp(value: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, value))
}
