import type { ArrangementBlock } from '../../deno/types.ts'

export type TemplateParam = {
  name: string
  label: string
  type: 'text' | 'number'
  defaultValue: string | number
}

export type DawTemplate = {
  id: string
  name: string
  category: string
  color: string
  defaultLengthBars: number
  code: string
  previewCode?: string
  params: TemplateParam[]
}

export const dawTemplates: DawTemplate[] = [
  {
    id: 'drums-four-on-floor',
    name: 'Four-on-floor kit',
    category: 'Drums',
    color: '#fb7185',
    defaultLengthBars: 4,
    code: 'drums({{seed}})',
    previewCode: 'drums(1) |> out($)',
    params: [{ name: 'seed', label: 'Seed', type: 'number', defaultValue: 1 }],
  },
  {
    id: 'drums-hat-grid',
    name: 'Hat pulse',
    category: 'Drums',
    color: '#f97316',
    defaultLengthBars: 2,
    code: 'ch(width:{{width}},trig:every({{rate}}))*.5',
    previewCode: 'ch(width:.75,trig:every(1/16))*.5 |> out($)',
    params: [
      { name: 'width', label: 'Width', type: 'number', defaultValue: 0.75 },
      { name: 'rate', label: 'Rate', type: 'text', defaultValue: '1/16' },
    ],
  },
  {
    id: 'drums-tight-kick',
    name: 'Tight kick',
    category: 'Drums',
    color: '#ef4444',
    defaultLengthBars: 2,
    code: "bd(trig:tram('{{pattern}}',{{bars}}))*{{gain}}",
    previewCode: "bd(trig:tram('x---x---',1))*0.9 |> out($)",
    params: [
      { name: 'pattern', label: 'Pattern', type: 'text', defaultValue: 'x---x---' },
      { name: 'bars', label: 'Bars', type: 'number', defaultValue: 1 },
      { name: 'gain', label: 'Gain', type: 'number', defaultValue: 0.9 },
    ],
  },
  {
    id: 'drums-backbeat-snare',
    name: 'Backbeat snare',
    category: 'Drums',
    color: '#fb7185',
    defaultLengthBars: 4,
    code: "sd(seed:{{seed}},trig:tram('{{pattern}}',{{bars}}))*{{gain}}",
    previewCode: "sd(seed:7,trig:tram('--x---x-',1))*0.75 |> out($)",
    params: [
      { name: 'pattern', label: 'Pattern', type: 'text', defaultValue: '--x---x-' },
      { name: 'bars', label: 'Bars', type: 'number', defaultValue: 1 },
      { name: 'seed', label: 'Seed', type: 'number', defaultValue: 7 },
      { name: 'gain', label: 'Gain', type: 'number', defaultValue: 0.75 },
    ],
  },
  {
    id: 'drums-open-hat',
    name: 'Open hat lift',
    category: 'Drums',
    color: '#fb923c',
    defaultLengthBars: 4,
    code: "oh(width:{{width}},trig:tram('{{pattern}}',{{bars}}))*{{gain}}",
    previewCode: "oh(width:.45,trig:tram('-x-x-x-x',1))*0.35 |> out($)",
    params: [
      { name: 'pattern', label: 'Pattern', type: 'text', defaultValue: '-x-x-x-x' },
      { name: 'bars', label: 'Bars', type: 'number', defaultValue: 1 },
      { name: 'width', label: 'Width', type: 'number', defaultValue: 0.45 },
      { name: 'gain', label: 'Gain', type: 'number', defaultValue: 0.35 },
    ],
  },
  {
    id: 'perc-rimshot',
    name: 'Rimshot',
    category: 'Percussion',
    color: '#f59e0b',
    defaultLengthBars: 2,
    code: "root='{{root}}'\nscale='{{scale}}'\ntrig=tram('{{pattern}}',{{bars}})\n;(white({{seed}},trig)+tri(#3*o{{octave}},trig))*ad(.001,.24,28,trig)*{{gain}} |> bp($,{{cutoff}},{{q}})",
    previewCode: "root='c3'\nscale='minor'\ntrig=tram('---x',1/2)\n;(white(11,trig)+tri(#3*o2,trig))*ad(.001,.24,28,trig)*.8 |> bp($,1800,.5) |> out($)",
    params: [
      { name: 'root', label: 'Root', type: 'text', defaultValue: 'c3' },
      { name: 'scale', label: 'Scale', type: 'text', defaultValue: 'minor' },
      { name: 'pattern', label: 'Pattern', type: 'text', defaultValue: '---x' },
      { name: 'bars', label: 'Bars', type: 'number', defaultValue: 0.5 },
      { name: 'seed', label: 'Seed', type: 'number', defaultValue: 11 },
      { name: 'octave', label: 'Octave', type: 'number', defaultValue: 2 },
      { name: 'cutoff', label: 'Cutoff', type: 'number', defaultValue: 1800 },
      { name: 'q', label: 'Q', type: 'number', defaultValue: 0.5 },
      { name: 'gain', label: 'Gain', type: 'number', defaultValue: 0.8 },
    ],
  },
  {
    id: 'perc-bongo',
    name: 'Bongo taps',
    category: 'Percussion',
    color: '#fbbf24',
    defaultLengthBars: 2,
    code: "trig=tram('{{pattern}}',{{bars}})\nsine([{{notes}}].random(every({{rate}})),trig)*ad(.001,.02,trig)*{{gain}}",
    previewCode: "trig=tram('-x-x-x-[xxx]',1)\nsine([180,300,500].random(every(1/16)),trig)*ad(.001,.02,trig)*.3 |> out($)",
    params: [
      { name: 'pattern', label: 'Pattern', type: 'text', defaultValue: '-x-x-x-[xxx]' },
      { name: 'bars', label: 'Bars', type: 'number', defaultValue: 1 },
      { name: 'notes', label: 'Notes', type: 'text', defaultValue: '180,300,500' },
      { name: 'rate', label: 'Rate', type: 'text', defaultValue: '1/16' },
      { name: 'gain', label: 'Gain', type: 'number', defaultValue: 0.3 },
    ],
  },
  {
    id: 'bass-walk',
    name: 'Walking bass',
    category: 'Bass',
    color: '#38bdf8',
    defaultLengthBars: 4,
    code: "root='{{root}}'\nscale='{{scale}}'\n;[#1,#3,#5,#7][t*{{speed}}] |> ntof($)*o{{octave}} |> saw($)*ad(trig:every({{rate}}))*.25 |> lp($,{{cutoff}},1)",
    previewCode: "root='c3'\nscale='minor'\n;[#1,#3,#5,#7][t*2] |> ntof($)*o1 |> saw($)*ad(trig:every(1/8))*.25 |> lp($,900,1) |> out($)",
    params: [
      { name: 'root', label: 'Root', type: 'text', defaultValue: 'c3' },
      { name: 'scale', label: 'Scale', type: 'text', defaultValue: 'minor' },
      { name: 'speed', label: 'Speed', type: 'number', defaultValue: 2 },
      { name: 'rate', label: 'Rate', type: 'text', defaultValue: '1/8' },
      { name: 'octave', label: 'Octave', type: 'number', defaultValue: 1 },
      { name: 'cutoff', label: 'Cutoff', type: 'number', defaultValue: 900 },
    ],
  },
  {
    id: 'bass-acid-line',
    name: 'Acid line',
    category: 'Bass',
    color: '#06b6d4',
    defaultLengthBars: 4,
    code: "root='{{root}}'\nscale='{{scale}}'\ntrig=tram('{{pattern}}',{{bars}})\nnote=[{{notes}}][t*{{speed}}]*o{{octave}}\nenv=ad(.004,.18,6,trig)\nramp(note) |> diodeladder($,{{cutoff}}+{{sweep}}*env,{{resonance}},.0025,{{drive}})*env*{{gain}}",
    previewCode: "root='c3'\nscale='minor'\ntrig=tram('x-xx-x--',1)\nnote=[#1,#1,#3,#5,#7][t*4]*o1\nenv=ad(.004,.18,6,trig)\nramp(note) |> diodeladder($,260+2600*env,.92,.0025,1.2)*env*.45 |> out($)",
    params: [
      { name: 'root', label: 'Root', type: 'text', defaultValue: 'c3' },
      { name: 'scale', label: 'Scale', type: 'text', defaultValue: 'minor' },
      { name: 'pattern', label: 'Pattern', type: 'text', defaultValue: 'x-xx-x--' },
      { name: 'bars', label: 'Bars', type: 'number', defaultValue: 1 },
      { name: 'notes', label: 'Notes', type: 'text', defaultValue: '#1,#1,#3,#5,#7' },
      { name: 'speed', label: 'Speed', type: 'number', defaultValue: 4 },
      { name: 'octave', label: 'Octave', type: 'number', defaultValue: 1 },
      { name: 'cutoff', label: 'Cutoff', type: 'number', defaultValue: 260 },
      { name: 'sweep', label: 'Sweep', type: 'number', defaultValue: 2600 },
      { name: 'resonance', label: 'Resonance', type: 'number', defaultValue: 0.92 },
      { name: 'drive', label: 'Drive', type: 'number', defaultValue: 1.2 },
      { name: 'gain', label: 'Gain', type: 'number', defaultValue: 0.45 },
    ],
  },
  {
    id: 'bass-sub-pulse',
    name: 'Sub pulse',
    category: 'Bass',
    color: '#0ea5e9',
    defaultLengthBars: 4,
    code: "root='{{root}}'\nscale='{{scale}}'\n;[{{notes}}][t*{{speed}}]*o{{octave}} |> tri($)*ad(.003,{{decay}},4,trig:tram('{{pattern}}',{{bars}})) |> lp($,{{cutoff}},{{q}})*{{gain}}",
    previewCode: "root='c2'\nscale='minor'\n;[#1,#5,#7,#5][t*2]*o1 |> tri($)*ad(.003,.42,4,trig:tram('x-x-',1)) |> lp($,120,.9)*.42 |> out($)",
    params: [
      { name: 'root', label: 'Root', type: 'text', defaultValue: 'c2' },
      { name: 'scale', label: 'Scale', type: 'text', defaultValue: 'minor' },
      { name: 'notes', label: 'Notes', type: 'text', defaultValue: '#1,#5,#7,#5' },
      { name: 'speed', label: 'Speed', type: 'number', defaultValue: 2 },
      { name: 'octave', label: 'Octave', type: 'number', defaultValue: 1 },
      { name: 'pattern', label: 'Pattern', type: 'text', defaultValue: 'x-x-' },
      { name: 'bars', label: 'Bars', type: 'number', defaultValue: 1 },
      { name: 'decay', label: 'Decay', type: 'number', defaultValue: 0.42 },
      { name: 'cutoff', label: 'Cutoff', type: 'number', defaultValue: 120 },
      { name: 'q', label: 'Q', type: 'number', defaultValue: 0.9 },
      { name: 'gain', label: 'Gain', type: 'number', defaultValue: 0.42 },
    ],
  },
  {
    id: 'melody-pluck',
    name: 'Pluck melody',
    category: 'Melody',
    color: '#a78bfa',
    defaultLengthBars: 4,
    code: "root='{{root}}'\nscale='{{scale}}'\n;[{{notes}}][t*{{speed}}] |> ntof($) |> tri($)*ad(.002,.25,trig:every({{rate}}))*.35",
    previewCode: "root='c4'\nscale='major'\n;[#1,#3,#5,#8][t*2] |> ntof($) |> tri($)*ad(.002,.25,trig:every(1/8))*.35 |> out($)",
    params: [
      { name: 'root', label: 'Root', type: 'text', defaultValue: 'c4' },
      { name: 'scale', label: 'Scale', type: 'text', defaultValue: 'major' },
      { name: 'notes', label: 'Notes', type: 'text', defaultValue: '#1,#3,#5,#8' },
      { name: 'speed', label: 'Speed', type: 'number', defaultValue: 2 },
      { name: 'rate', label: 'Rate', type: 'text', defaultValue: '1/8' },
    ],
  },
  {
    id: 'melody-euclid-pluck',
    name: 'Euclid pluck',
    category: 'Melody',
    color: '#8b5cf6',
    defaultLengthBars: 4,
    code: "root='{{root}}'\nscale='{{scale}}'\ntrig=euclid({{pulses}},{{steps}},{{offset}},bar:{{bars}})\n;[{{notes}}][t*{{speed}}] |> ntof($)*o{{octave}} |> saw($)*ad(.002,{{decay}},4,trig) |> lp($,{{cutoff}},1)*{{gain}}",
    previewCode: "root='c4'\nscale='dorian'\ntrig=euclid(5,8,0,bar:1/2)\n;[#1,#3,#4,#5,#7][t*3] |> ntof($)*o1 |> saw($)*ad(.002,.28,4,trig) |> lp($,2200,1)*.32 |> out($)",
    params: [
      { name: 'root', label: 'Root', type: 'text', defaultValue: 'c4' },
      { name: 'scale', label: 'Scale', type: 'text', defaultValue: 'dorian' },
      { name: 'notes', label: 'Notes', type: 'text', defaultValue: '#1,#3,#4,#5,#7' },
      { name: 'speed', label: 'Speed', type: 'number', defaultValue: 3 },
      { name: 'octave', label: 'Octave', type: 'number', defaultValue: 1 },
      { name: 'pulses', label: 'Pulses', type: 'number', defaultValue: 5 },
      { name: 'steps', label: 'Steps', type: 'number', defaultValue: 8 },
      { name: 'offset', label: 'Offset', type: 'number', defaultValue: 0 },
      { name: 'bars', label: 'Bars', type: 'number', defaultValue: 0.5 },
      { name: 'decay', label: 'Decay', type: 'number', defaultValue: 0.28 },
      { name: 'cutoff', label: 'Cutoff', type: 'number', defaultValue: 2200 },
      { name: 'gain', label: 'Gain', type: 'number', defaultValue: 0.32 },
    ],
  },
  {
    id: 'melody-mini-saw',
    name: 'Step saw phrase',
    category: 'Melody',
    color: '#c084fc',
    defaultLengthBars: 4,
    code: ";[{{notes}}][t*{{speed}}] |> ntof($) |> saw($)*ad(.002,{{decay}},4,trig:every({{rate}})) |> lp($,{{cutoff}},1)*{{gain}}",
    previewCode: ";[60,63,67,70][t*3] |> ntof($) |> saw($)*ad(.002,.28,4,trig:every(1/8)) |> lp($,2400,1)*.3 |> out($)",
    params: [
      { name: 'notes', label: 'Notes', type: 'text', defaultValue: '60,63,67,70' },
      { name: 'speed', label: 'Speed', type: 'number', defaultValue: 3 },
      { name: 'rate', label: 'Rate', type: 'text', defaultValue: '1/8' },
      { name: 'decay', label: 'Decay', type: 'number', defaultValue: 0.28 },
      { name: 'cutoff', label: 'Cutoff', type: 'number', defaultValue: 2400 },
      { name: 'gain', label: 'Gain', type: 'number', defaultValue: 0.3 },
    ],
  },
  {
    id: 'chords-house-stab',
    name: 'House chord stab',
    category: 'Chords',
    color: '#22c55e',
    defaultLengthBars: 4,
    code: "trig=tram('{{pattern}}',{{bars}})\n;[{{chord}}].map(hz->saw(hz)+saw(hz*1.5)).avg()/{{voices}}*ad(.05,{{decay}},trig)\n|> lp($,{{cutoff}}+{{sweep}}*ad(.01,.5,trig),{{q}}) |> $+dattorro($)*{{reverb}}",
    previewCode: "trig=tram('-x',1/4)\n;[e3,a3,c4].map(hz->saw(hz)+saw(hz*1.5)).avg()/7*ad(.05,.4,trig)\n|> lp($,200+700*ad(.01,.5,trig),.5) |> $+dattorro($)*1.2 |> out($)",
    params: [
      { name: 'pattern', label: 'Pattern', type: 'text', defaultValue: '-x' },
      { name: 'bars', label: 'Bars', type: 'number', defaultValue: 0.25 },
      { name: 'chord', label: 'Chord', type: 'text', defaultValue: 'e3,a3,c4' },
      { name: 'voices', label: 'Voices', type: 'number', defaultValue: 7 },
      { name: 'decay', label: 'Decay', type: 'number', defaultValue: 0.4 },
      { name: 'cutoff', label: 'Cutoff', type: 'number', defaultValue: 200 },
      { name: 'sweep', label: 'Sweep', type: 'number', defaultValue: 700 },
      { name: 'q', label: 'Q', type: 'number', defaultValue: 0.5 },
      { name: 'reverb', label: 'Reverb', type: 'number', defaultValue: 1.2 },
    ],
  },
  {
    id: 'chords-rhodes',
    name: 'Rhodes comp',
    category: 'Chords',
    color: '#4ade80',
    defaultLengthBars: 4,
    code: "root='{{root}}'\nscale='{{scale}}'\ntrig=tram('{{pattern}}',{{bars}})\n;[{{chord}}].map(hz->rhodes(hz*o{{octave}},trig:trig)).avg()*{{gain}} |> chorus($,{{voices}},{{base}},{{depth}},{{rate}},.5)",
    previewCode: "root='c3'\nscale='major'\ntrig=tram('x--x-x--',1)\n;[#1,#3,#5,#7].map(hz->rhodes(hz*o2,trig:trig)).avg()*.42 |> chorus($,3,.02,.006,.25,.5) |> out($)",
    params: [
      { name: 'root', label: 'Root', type: 'text', defaultValue: 'c3' },
      { name: 'scale', label: 'Scale', type: 'text', defaultValue: 'major' },
      { name: 'pattern', label: 'Pattern', type: 'text', defaultValue: 'x--x-x--' },
      { name: 'bars', label: 'Bars', type: 'number', defaultValue: 1 },
      { name: 'chord', label: 'Chord', type: 'text', defaultValue: '#1,#3,#5,#7' },
      { name: 'octave', label: 'Octave', type: 'number', defaultValue: 2 },
      { name: 'voices', label: 'Voices', type: 'number', defaultValue: 3 },
      { name: 'base', label: 'Base', type: 'number', defaultValue: 0.02 },
      { name: 'depth', label: 'Depth', type: 'number', defaultValue: 0.006 },
      { name: 'rate', label: 'Rate', type: 'number', defaultValue: 0.25 },
      { name: 'gain', label: 'Gain', type: 'number', defaultValue: 0.42 },
    ],
  },
  {
    id: 'pad-slow',
    name: 'Slow pad',
    category: 'Pads',
    color: '#34d399',
    defaultLengthBars: 8,
    code: "root='{{root}}'\nscale='{{scale}}'\n;([#1,#3,#5,#7]*o{{octave}}).map(saw).avg()*timeline('1,0 2,1e2 7,1 8,0e2',{{color}})*.18 |> lp($,{{cutoff}},1)",
    previewCode: "root='c3'\nscale='major'\n;([#1,#3,#5,#7]*o1).map(saw).avg()*timeline('1,0 2,1e2 7,1 8,0e2',2)*.18 |> lp($,1200,1) |> out($)",
    params: [
      { name: 'root', label: 'Root', type: 'text', defaultValue: 'c3' },
      { name: 'scale', label: 'Scale', type: 'text', defaultValue: 'major' },
      { name: 'octave', label: 'Octave', type: 'number', defaultValue: 1 },
      { name: 'cutoff', label: 'Cutoff', type: 'number', defaultValue: 1200 },
      { name: 'color', label: 'Color', type: 'number', defaultValue: 2 },
    ],
  },
  {
    id: 'pad-supersaw-cloud',
    name: 'Supersaw cloud',
    category: 'Pads',
    color: '#10b981',
    defaultLengthBars: 8,
    code: "root='{{root}}'\nscale='{{scale}}'\n;([{{chord}}]*o{{octave}}).map(hz->supersaw(hz,{{voices}},{{spread}})).avg()*timeline('1,0 2,1e2 7,1 8,0e2',{{color}})*{{gain}} |> lp($,{{cutoff}},{{q}}) |> chorus($,4,.025,.008,.18,.5)",
    previewCode: "root='c3'\nscale='major'\n;([#1,#3,#5,#9]*o1).map(hz->supersaw(hz,7,.035)).avg()*timeline('1,0 2,1e2 7,1 8,0e2',2)*.18 |> lp($,1800,.8) |> chorus($,4,.025,.008,.18,.5) |> out($)",
    params: [
      { name: 'root', label: 'Root', type: 'text', defaultValue: 'c3' },
      { name: 'scale', label: 'Scale', type: 'text', defaultValue: 'major' },
      { name: 'chord', label: 'Chord', type: 'text', defaultValue: '#1,#3,#5,#9' },
      { name: 'octave', label: 'Octave', type: 'number', defaultValue: 1 },
      { name: 'voices', label: 'Voices', type: 'number', defaultValue: 7 },
      { name: 'spread', label: 'Spread', type: 'number', defaultValue: 0.035 },
      { name: 'cutoff', label: 'Cutoff', type: 'number', defaultValue: 1800 },
      { name: 'q', label: 'Q', type: 'number', defaultValue: 0.8 },
      { name: 'gain', label: 'Gain', type: 'number', defaultValue: 0.18 },
      { name: 'color', label: 'Color', type: 'number', defaultValue: 2 },
    ],
  },
  {
    id: 'pad-dark-drone',
    name: 'Dark drone',
    category: 'Pads',
    color: '#14b8a6',
    defaultLengthBars: 8,
    code: "root='{{root}}'\nscale='{{scale}}'\n;(supersaw(#1*o{{octave}},{{voices}},{{spread}})+supersaw(#5*o{{octave}},{{voices}},{{spread}}))*.5*timeline('1,0 2,1e2 8,1',{{color}})*{{gain}} |> lp($,{{cutoff}}+{{movement}}*lfotri({{cycle}}),{{q}}) |> dattorro($,{{room}},{{damping}})",
    previewCode: "root='c2'\nscale='minor'\n;(supersaw(#1*o2,5,.025)+supersaw(#5*o2,5,.025))*.5*timeline('1,0 2,1e2 8,1',4)*.16 |> lp($,500+900*lfotri(4),.85) |> dattorro($,.55,.45) |> out($)",
    params: [
      { name: 'root', label: 'Root', type: 'text', defaultValue: 'c2' },
      { name: 'scale', label: 'Scale', type: 'text', defaultValue: 'minor' },
      { name: 'octave', label: 'Octave', type: 'number', defaultValue: 2 },
      { name: 'voices', label: 'Voices', type: 'number', defaultValue: 5 },
      { name: 'spread', label: 'Spread', type: 'number', defaultValue: 0.025 },
      { name: 'cycle', label: 'Cycle', type: 'number', defaultValue: 4 },
      { name: 'cutoff', label: 'Cutoff', type: 'number', defaultValue: 500 },
      { name: 'movement', label: 'Movement', type: 'number', defaultValue: 900 },
      { name: 'q', label: 'Q', type: 'number', defaultValue: 0.85 },
      { name: 'room', label: 'Room', type: 'number', defaultValue: 0.55 },
      { name: 'damping', label: 'Damping', type: 'number', defaultValue: 0.45 },
      { name: 'gain', label: 'Gain', type: 'number', defaultValue: 0.16 },
      { name: 'color', label: 'Color', type: 'number', defaultValue: 4 },
    ],
  },
  {
    id: 'fx-riser',
    name: 'Noise riser',
    category: 'FX',
    color: '#facc15',
    defaultLengthBars: 4,
    code: "white({{seed}})*timeline('1,0 4,1e2 -',{{color}}) |> hp($,200+8k*timeline('1,0 4,1e2 -',{{color}}),1)*.25",
    previewCode: "white(4)*timeline('1,0 4,1e2 -',2) |> hp($,200+8k*timeline('1,0 4,1e2 -',2),1)*.25 |> out($)",
    params: [
      { name: 'seed', label: 'Seed', type: 'number', defaultValue: 4 },
      { name: 'color', label: 'Color', type: 'number', defaultValue: 2 },
    ],
  },
  {
    id: 'fx-downlifter',
    name: 'Noise downlifter',
    category: 'FX',
    color: '#fde047',
    defaultLengthBars: 4,
    code: "white({{seed}})*timeline('1,1 4,0e2 -',{{color}}) |> hp($,{{high}}-{{fall}}*timeline('1,0 4,1e2 -',{{color}}),1)*{{gain}}",
    previewCode: "white(9)*timeline('1,1 4,0e2 -',2) |> hp($,9000-7600*timeline('1,0 4,1e2 -',2),1)*.22 |> out($)",
    params: [
      { name: 'seed', label: 'Seed', type: 'number', defaultValue: 9 },
      { name: 'high', label: 'High', type: 'number', defaultValue: 9000 },
      { name: 'fall', label: 'Fall', type: 'number', defaultValue: 7600 },
      { name: 'gain', label: 'Gain', type: 'number', defaultValue: 0.22 },
      { name: 'color', label: 'Color', type: 'number', defaultValue: 2 },
    ],
  },
  {
    id: 'fx-delay-pings',
    name: 'Delay pings',
    category: 'FX',
    color: '#eab308',
    defaultLengthBars: 4,
    code: "trig=tram('{{pattern}}',{{bars}})\n;[{{notes}}][t*{{speed}}] |> ntof($) |> tri($)*ad(.002,{{decay}},6,trig)*{{gain}} |> delay($,{{time}},{{feedback}})",
    previewCode: "trig=tram('x---x-x-',1)\n;[72,79,84,91][t*3] |> ntof($) |> tri($)*ad(.002,.12,6,trig)*.28 |> delay($,.18,.45) |> out($)",
    params: [
      { name: 'pattern', label: 'Pattern', type: 'text', defaultValue: 'x---x-x-' },
      { name: 'bars', label: 'Bars', type: 'number', defaultValue: 1 },
      { name: 'notes', label: 'Notes', type: 'text', defaultValue: '72,79,84,91' },
      { name: 'speed', label: 'Speed', type: 'number', defaultValue: 3 },
      { name: 'decay', label: 'Decay', type: 'number', defaultValue: 0.12 },
      { name: 'time', label: 'Time', type: 'number', defaultValue: 0.18 },
      { name: 'feedback', label: 'Feedback', type: 'number', defaultValue: 0.45 },
      { name: 'gain', label: 'Gain', type: 'number', defaultValue: 0.28 },
    ],
  },
]

export function getTemplate(id: string | undefined): DawTemplate | undefined {
  return id ? dawTemplates.find(template => template.id === id) : undefined
}

export function defaultTemplateParams(template: DawTemplate): ArrangementBlock['params'] {
  return Object.fromEntries(template.params.map(param => [param.name, param.defaultValue]))
}

export function renderTemplateCode(template: DawTemplate, params: ArrangementBlock['params']): string {
  return template.code.replace(/\{\{(\w+)\}\}/g, (_, key: string) => String(params[key] ?? ''))
}
